/** Моковые данные для локального тестирования каталога и поиска */

export type SeedSupplierRow = { slug: string; name: string };

export type SeedCategoryRow = { slug: string; name: string; parentId: null };

export type SeedProductRow = {
  slug: string;
  name: string;
  sku: string | null;
  article: string | null;
  price: string;
  /** Цена в UI — «По запросу»; в БД остаётся числовое `price` для сортировки. */
  priceOnRequest?: boolean;
  stockQuantity: number;
  lastUpdatedAt: string;
  supplierSlug: string;
  categorySlug: string;
};

export const SEED_SUPPLIERS: SeedSupplierRow[] = [
  { slug: 'ivanov-partners', name: 'ООО «Иванов и партнеры»' },
  { slug: 'ivanov-kompaniya', name: 'ООО «Иванов и Компания»' },
  { slug: 'electro-snab', name: 'ООО «ЭлектроСнаб»' },
  { slug: 'kabel-profi', name: 'ООО «КабельПрофи»' },
  { slug: 'svet-torg', name: 'ООО «СветТорг»' },
  { slug: 'elektrokomplekt', name: 'АО «Электрокомплект»' },
  { slug: 'moskabel', name: 'ООО «Москабель»' },
];

export const SEED_CATEGORIES: SeedCategoryRow[] = [
  { slug: 'cable', name: 'Кабель и провод', parentId: null },
  { slug: 'equipment', name: 'Электрооборудование', parentId: null },
  { slug: 'switchgear', name: 'Распределительные устройства', parentId: null },
  { slug: 'lighting', name: 'Светотехника', parentId: null },
];

export const SEED_PRODUCTS: SeedProductRow[] = [
  {
    slug: 'vvgng-ls-3x2-5',
    name: 'Кабель ВВГнг(А)-LS 3х2,5',
    sku: 'VGNG-3x2.5',
    article: '254634',
    price: '118.30',
    stockQuantity: 8000,
    lastUpdatedAt: '2026-02-17',
    supplierSlug: 'ivanov-partners',
    categorySlug: 'cable',
  },
  {
    slug: 'vvgng-ls-3x1-5',
    name: 'Кабель ВВГнг(А)-LS 3х1,5',
    sku: 'VGNG-3x1.5',
    article: '254635',
    price: '89.50',
    stockQuantity: 12000,
    lastUpdatedAt: '2026-02-16',
    supplierSlug: 'ivanov-partners',
    categorySlug: 'cable',
  },
  {
    slug: 'vvgng-ls-5x4',
    name: 'Кабель ВВГнг(А)-LS 5х4',
    sku: 'VGNG-5x4',
    article: '254640',
    price: '312.00',
    stockQuantity: 2100,
    lastUpdatedAt: '2026-02-15',
    supplierSlug: 'moskabel',
    categorySlug: 'cable',
  },
  {
    slug: 'vvg-3x2-5',
    name: 'Кабель ВВГ 3х2,5',
    sku: 'VVG-3x2.5',
    article: '301001',
    price: '72.40',
    stockQuantity: 15000,
    lastUpdatedAt: '2026-02-14',
    supplierSlug: 'kabel-profi',
    categorySlug: 'cable',
  },
  {
    slug: 'avvg-4x120',
    name: 'Кабель АВВГ 4×120',
    sku: 'AVVG-4x120',
    article: '881201',
    price: '4520.00',
    priceOnRequest: true,
    stockQuantity: 400,
    lastUpdatedAt: '2026-02-10',
    supplierSlug: 'electro-snab',
    categorySlug: 'cable',
  },
  {
    slug: 'pvs-3x2-5',
    name: 'Провод ПВС 3х2,5',
    sku: 'PVS-3x2.5',
    article: '410022',
    price: '45.20',
    stockQuantity: 9000,
    lastUpdatedAt: '2026-02-12',
    supplierSlug: 'kabel-profi',
    categorySlug: 'cable',
  },
  {
    slug: 'puv-1x10',
    name: 'Провод ПуВ 1×10',
    sku: 'PUV-1x10',
    article: '410088',
    price: '128.00',
    stockQuantity: 3200,
    lastUpdatedAt: '2026-02-08',
    supplierSlug: 'moskabel',
    categorySlug: 'cable',
  },
  {
    slug: 'avb-63a',
    name: 'Автоматический выключатель 63А',
    sku: 'MCB-63',
    article: '990011',
    price: '1240.00',
    stockQuantity: 250,
    lastUpdatedAt: '2026-01-28',
    supplierSlug: 'electro-snab',
    categorySlug: 'equipment',
  },
  {
    slug: 'avb-25a-b',
    name: 'Автоматический выключатель 25А, характеристика B',
    sku: 'MCB-25-B',
    article: '990012',
    price: '890.00',
    stockQuantity: 480,
    lastUpdatedAt: '2026-02-01',
    supplierSlug: 'elektrokomplekt',
    categorySlug: 'equipment',
  },
  {
    slug: 'kontaktor-40a',
    name: 'Контактор модульный 40А',
    sku: 'KM-40',
    article: '770055',
    price: '2150.00',
    stockQuantity: 120,
    lastUpdatedAt: '2026-01-20',
    supplierSlug: 'elektrokomplekt',
    categorySlug: 'equipment',
  },
  {
    slug: 'rubezh-12m',
    name: 'УЗО 2P 63А 30мА',
    sku: 'RCD-2P-63',
    article: '660033',
    price: '1890.00',
    stockQuantity: 95,
    lastUpdatedAt: '2026-02-05',
    supplierSlug: 'electro-snab',
    categorySlug: 'equipment',
  },
  {
    slug: 'schit-nakladnoy-12',
    name: 'Щит распределительный накладной на 12 модулей',
    sku: 'DB-12-S',
    article: '520100',
    price: '1450.00',
    stockQuantity: 200,
    lastUpdatedAt: '2026-02-11',
    supplierSlug: 'ivanov-partners',
    categorySlug: 'switchgear',
  },
  {
    slug: 'schit-vstraivaemyy-24',
    name: 'Щит встраиваемый на 24 модуля IP40',
    sku: 'DB-24-F',
    article: '520124',
    price: '2890.00',
    stockQuantity: 88,
    lastUpdatedAt: '2026-01-30',
    supplierSlug: 'elektrokomplekt',
    categorySlug: 'switchgear',
  },
  {
    slug: 'avr-63a',
    name: 'Автоматический ввод резерва 63А',
    sku: 'ATS-63',
    article: '530200',
    price: '12400.00',
    stockQuantity: 15,
    lastUpdatedAt: '2026-01-15',
    supplierSlug: 'elektrokomplekt',
    categorySlug: 'switchgear',
  },
  {
    slug: 'svetilnik-led-36w',
    name: 'Светильник LED панель 595×595 36 Вт 4000K',
    sku: 'LED-PAN-36',
    article: '610301',
    price: '1680.00',
    stockQuantity: 340,
    lastUpdatedAt: '2026-02-13',
    supplierSlug: 'svet-torg',
    categorySlug: 'lighting',
  },
  {
    slug: 'prozhektor-led-50w',
    name: 'Прожектор LED 50 Вт IP65',
    sku: 'FL-LED-50',
    article: '610450',
    price: '920.00',
    stockQuantity: 560,
    lastUpdatedAt: '2026-02-09',
    supplierSlug: 'svet-torg',
    categorySlug: 'lighting',
  },
  {
    slug: 'lampa-led-e27-10w',
    name: 'Лампа LED Е27 10 Вт 3000K',
    sku: 'LED-E27-10',
    article: '620011',
    price: '125.00',
    stockQuantity: 8000,
    lastUpdatedAt: '2026-02-17',
    supplierSlug: 'svet-torg',
    categorySlug: 'lighting',
  },
  {
    slug: 'kabel-nym-3x1-5',
    name: 'Кабель NYM 3×1,5',
    sku: 'NYM-3x1.5',
    article: '330501',
    price: '38.90',
    stockQuantity: 11000,
    lastUpdatedAt: '2026-02-06',
    supplierSlug: 'moskabel',
    categorySlug: 'cable',
  },
  {
    slug: 'sip-4x16',
    name: 'Провод СИП-4 4×16',
    sku: 'SIP-4x16',
    article: '340120',
    price: '95.00',
    stockQuantity: 4200,
    lastUpdatedAt: '2026-02-04',
    supplierSlug: 'kabel-profi',
    categorySlug: 'cable',
  },
  {
    slug: 'transformato-630',
    name: 'Трансформатор силовой 630 кВА',
    sku: 'TR-630',
    article: '800001',
    price: '285000.00',
    priceOnRequest: true,
    stockQuantity: 3,
    lastUpdatedAt: '2025-12-01',
    supplierSlug: 'elektrokomplekt',
    categorySlug: 'equipment',
  },
  {
    slug: 'schetchik-merkuriy-201',
    name: 'Счётчик электроэнергии однофазный Меркурий 201',
    sku: 'M201',
    article: '710010',
    price: '2340.00',
    stockQuantity: 180,
    lastUpdatedAt: '2026-02-03',
    supplierSlug: 'ivanov-partners',
    categorySlug: 'equipment',
  },
  {
    slug: 'kabel-vbshv-3h16',
    name: 'Кабель ВБШв 3х16',
    sku: 'VVGNG-3x2.5',
    article: 'VVGNG-3x2.5',
    price: '118.30',
    stockQuantity: 8000,
    lastUpdatedAt: '2026-02-17',
    supplierSlug: 'ivanov-partners',
    categorySlug: 'cable',
  },
];
